displayName=Blast Mine Tracker
author=xiler
description=Tracks blast mine statistics as you blast
tags=blast mine, blast mine statistics, blast mine tracker, improved blast mine, blast mining, mining, xiler
plugins=blastminetracker.BlastMineTrackerPlugin